const firstDishes = {
    header: 'Первые блюда',
    products: [
        {
            imgLink: '/img/temporary/kebab1.jpg',
            name: 'Хашлама',
            description: 'Баранина супер вкусная',
            dose: '200' ,
            calculation: 'гр',
            price: '160',
        },
        {
            imgLink: '/img/temporary/kebab2.jpg',
            name: 'Жульен с Курицей',
            description: 'Куриное филле',
            dose: '200' ,
            calculation: 'гр',
            price: '160',
        },
        {
            imgLink: '/img/temporary/kebab1.jpg',
            name: 'Говдина в горшке',
            description: 'Горшок из глины хранит тепло и нежный вкус еды',
            dose: '200' ,
            calculation: 'гр',
            price: '160',
        },
        {
            imgLink: '/img/temporary/kebab2.jpg',
            name: 'Хашлама',
            description: 'Баранина супер вкусная',
            dose: '200' ,
            calculation: 'гр',
            price: '160',
        },
        {
            imgLink: '/img/temporary/kebab1.jpg',
            name: 'Жульен с Курицей',
            description: 'Куриное филле',
            dose: '200' ,
            calculation: 'гр',
            price: '160',
        },
        {
            imgLink: '/img/temporary/kebab2.jpg',
            name: 'Говдина в горшке',
            description: 'Горшок из глины хранит тепло и нежный вкус еды',
            dose: '200' ,
            calculation: 'гр',
            price: '160',
        },
    ],
};

const secondDishes = {
    header: 'Вторые блюда',
    products: [
        {
            imgLink: '/img/temporary/soup.jpg',
            name: 'Хашлама',
            description: 'Баранина супер вкусная',
            dose: '200' ,
            calculation: 'гр',
            price: '160',
        },
        {
            imgLink: '/img/temporary/soup.jpg',
            name: 'Жульен с Курицей',
            description: 'Куриное филле',
            dose: '200' ,
            calculation: 'гр',
            price: '160',
        },
        {
            imgLink: '/img/temporary/soup.jpg',
            name: 'Говдина в горшке',
            description: 'Горшок из глины хранит тепло и нежный вкус еды',
            dose: '200' ,
            calculation: 'гр',
            price: '160',
        },
        {
            imgLink: '/img/temporary/soup.jpg',
            name: 'Хашлама',
            description: 'Баранина супер вкусная',
            dose: '200' ,
            calculation: 'гр',
            price: '160',
        },
        {
            imgLink: '/img/temporary/soup.jpg',
            name: 'Жульен с Курицей',
            description: 'Куриное филле',
            dose: '200' ,
            calculation: 'гр',
            price: '160',
        },
        {
            imgLink: '/img/temporary/soup.jpg',
            name: 'Говдина в горшке',
            description: 'Горшок из глины хранит тепло и нежный вкус еды',
            dose: '200' ,
            calculation: 'гр',
            price: '160',
        },
    ],
};

const drinks = {
    header: 'Напитки',
    products: [
        {
            imgLink: '/img/temporary/drink.jpg',
            name: 'Хашлама',
            description: 'Баранина супер вкусная',
            dose: '200' ,
            calculation: 'мл',
            price: '160',
        },
        {
            imgLink: '/img/temporary/drink.jpg',
            name: 'Жульен с Курицей',
            description: 'Куриное филле',
            dose: '200' ,
            calculation: 'мл',
            price: '160',
        },
        {
            imgLink: '/img/temporary/drink.jpg',
            name: 'Говдина в горшке',
            description: 'Горшок из глины хранит тепло и нежный вкус еды',
            dose: '200' ,
            calculation: 'мл',
            price: '160',
        },
        {
            imgLink: '/img/temporary/drink.jpg',
            name: 'Хашлама',
            description: 'Баранина супер вкусная',
            dose: '200' ,
            calculation: 'мл',
            price: '160',
        },
        {
            imgLink: '/img/temporary/drink.jpg',
            name: 'Жульен с Курицей',
            description: 'Куриное филле',
            dose: '200' ,
            calculation: 'мл',
            price: '160',
        },
        {
            imgLink: '/img/temporary/drink.jpg',
            name: 'Говдина в горшке',
            description: 'Горшок из глины хранит тепло и нежный вкус еды',
            dose: '200' ,
            calculation: 'мл',
            price: '160',
        },
    ],
};

const garnirs = {
    header: 'Гарниры',
    products: [
        {
            imgLink: '/img/temporary/garnish.jpg',
            name: 'Хашлама',
            description: 'Баранина супер вкусная!',
            dose: '200' ,
            calculation: 'гр',
            price: '160',
        },
        {
            imgLink: '/img/temporary/garnish.jpg',
            name: 'Жульен с КУрицей',
            description: 'Куриное филле',
            dose: '200' ,
            calculation: 'гр',
            price: '160',
        },
        {
            imgLink: '/img/temporary/garnish.jpg',
            name: 'Говдина в горшке',
            description: 'Горшок из глины хранит тепло и нежный вкус еды',
            dose: '200' ,
            calculation: 'гр',
            price: '160',
        },
        {
            imgLink: '/img/temporary/garnish.jpg',
            name: 'Хашлама',
            description: 'Баранина супер вкусная',
            dose: '200' ,
            calculation: 'гр',
            price: '160',
        },
        {
            imgLink: '/img/temporary/garnish.jpg',
            name: 'Жульен с Курицей',
            description: 'Куриное филле',
            dose: '200' ,
            calculation: 'гр',
            price: '160',
        },
        {
            imgLink: '/img/temporary/garnish.jpg',
            name: 'Говдина в горшке',
            description: 'Горшок из глины хранит тепло и нежный вкус еды',
            dose: '200' ,
            calculation: 'гр',
            price: '160',
        },
    ],
};

const salats = {
    header: 'Салаты',
    products: [
        {
            imgLink: '/img/temporary/salat1.jpg',
            name: 'Хашлама',
            description: 'Баранина супер вкусная',
            dose: '200' ,
            calculation: 'гр',
            price: '160',
        },
        {
            imgLink: '/img/temporary/salat2.jpg',
            name: 'Жульен с Курицей',
            description: 'Куриное филле',
            dose: '200' ,
            calculation: 'гр',
            price: '160',
        },
        {
            imgLink: '/img/temporary/salat1.jpg',
            name: 'Говдина в горшке',
            description: 'Горшок из глины хранит тепло и нежный вкус еды',
            dose: '200' ,
            calculation: 'гр',
            price: '160',
        },
        {
            imgLink: '/img/temporary/salat2.jpg',
            name: 'Хашлама',
            description: 'Баранина супер вкусная',
            dose: '200' ,
            calculation: 'гр',
            price: '160',
        },
        {
            imgLink: '/img/temporary/salat1.jpg',
            name: 'Жульен с Курицей',
            description: 'Куриное филле',
            dose: '200' ,
            calculation: 'гр',
            price: '160',
        },
        {
            imgLink: '/img/temporary/salat2.jpg',
            name: 'Говдина в горшке',
            description: 'Горшок из глины хранит тепло и нежный вкус еды',
            dose: '200' ,
            calculation: 'гр',
            price: '160',
        },
    ],
};

const beer = {
    header: 'Пивная карта',
    products: [
        {
            imgLink: '/img/temporary/beer.jpg',
            name: 'Хашлама',
            description: 'Баранина супер вкусная',
            dose: '300' ,
            calculation: 'мл',
            price: '160',
        },
        {
            imgLink: '/img/temporary/beer.jpg',
            name: 'Жульен с Куицей',
            description: 'Куриное филле',
            dose: '300' ,
            calculation: 'мл',
            price: '160',
        },
        {
            imgLink: '/img/temporary/beer.jpg',
            name: 'Говдина в горшке',
            description: 'Горшок из глины хранит тепло и нежный вкус еды',
            dose: '300' ,
            calculation: 'мл',
            price: '160',
        },
        {
            imgLink: '/img/temporary/beer.jpg',
            name: 'Хашлама',
            description: 'Баранина супер вкусная',
            dose: '300' ,
            calculation: 'мл',
            price: '160',
        },
        {
            imgLink: '/img/temporary/beer.jpg',
            name: 'Жульен с Курицей',
            description: 'Куриное филле',
            dose: '300' ,
            calculation: 'мл',
            price: '160',
        },
        {
            imgLink: '/img/temporary/beer.jpg',
            name: 'Говдина в горшке',
            description: 'Горшок из глины хранит тепло и нежный вкус еды',
            dose: '300' ,
            calculation: 'мл',
            price: '160',
        },
    ],
};

const snacks = {
    header: 'Закуски',
    products: [
        {
            imgLink: '/img/temporary/snaks2.jpg',
            name: 'Хашлама',
            description: 'Баранина супер вкусная',
            dose: '300' ,
            calculation: 'гр',
            price: '160',
        },
        {
            imgLink: '/img/temporary/snaks1.jpg',
            name: 'Жульен с Курицей',
            description: 'Куриное филле',
            dose: '300' ,
            calculation: 'гр',
            price: '160',
        },
        {
            imgLink: '/img/temporary/snaks2.jpg',
            name: 'Говдина в горшке',
            description: 'Горшок из глины хранит тепло и нежный вкус еды',
            dose: '300' ,
            calculation: 'гр',
            price: '160',
        },
        {
            imgLink: '/img/temporary/snaks1.jpg',
            name: 'Хашлама',
            description: 'Баранина супер вкусная',
            dose: '300' ,
            calculation: 'гр',
            price: '160',
        },
        {
            imgLink: '/img/temporary/snaks1.jpg',
            name: 'Жульен с КУрицей',
            description: 'Куриное филле',
            dose: '300' ,
            calculation: 'гр',
            price: '160',
        },
        {
            imgLink: '/img/temporary/snaks2.jpg',
            name: 'Говдина в горшке',
            description: 'Горшок из глины хранит тепло и нежный вкус еды',
            dose: '300' ,
            calculation: 'гр',
            price: '160',
        },
    ],
};

const brazier = {
    header: 'Блюда на мангале',
    products: [
        {
            imgLink: '/img/temporary/kebab2.jpg',
            name: 'Хашлама',
            description: 'Баранина супер вкусная',
            dose: '300' ,
            calculation: 'гр',
            price: '160',
        },
        {
            imgLink: '/img/temporary/kebab1.jpg',
            name: 'Жульен с КУрицей',
            description: 'Куриное филле',
            dose: '300' ,
            calculation: 'гр',
            price: '160',
        },
        {
            imgLink: '/img/temporary/kebab2.jpg',
            name: 'Говдина в горшке',
            description: 'Горшок из глины хранит тепло и нежный вкус еды',
            dose: '300' ,
            calculation: 'гр',
            price: '160',
        },
        {
            imgLink: '/img/temporary/kebab1.jpg',
            name: 'Хашлама',
            description: 'Баранина супер вкусная',
            dose: '300' ,
            calculation: 'гр',
            price: '160',
        },
        {
            imgLink: '/img/temporary/kebab2.jpg',
            name: 'Жульен с Курицей',
            description: 'Куриное филле',
            dose: '300' ,
            calculation: 'гр',
            price: '160',
        },
        {
            imgLink: '/img/temporary/kebab1.jpg',
            name: 'Говдина в горшке',
            description: 'Горшок из глины хранит тепло и нежный вкус еды',
            dose: '300' ,
            calculation: 'гр',
            price: '160',
        },
    ],
};

const productsArray = [firstDishes, secondDishes, drinks, garnirs, salats, beer, snacks, brazier];

export default productsArray;
